<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../../components/Nav.svelte";
    import Footer from "../../../../components/Footer.svelte";
    export let data;
    const post = {
  "url": "/en/blog/gaia-charge-launches-online-store",
  "frontmatter": {
    "title": "Gaia Charge Launches New Online Store to Strengthen Access to EV Charging Equipment in Spain",
    "date": "2025-06-19T00:00:00.000Z",
    "updated": "2025-08-11T10:10:00.000Z",
    "notion_id": "24ce5620-ab7b-8075-b3d7-e82d4269934c",
    "author": "Wojtek Siudzinski",
    "language": "english",
    "slug": "gaia-charge-launches-online-store"
  },
  "content": "<p>Gaia Charge announces the launch of its new online store, a strategic step to make the deployment of electric vehicle (EV) charging infrastructure in Spain more accessible, professional, and efficient.</p>\n<p>The platform offers a curated selection of certified chargers, accessories, and components from leading manufacturers such as CIRCUTOR and V2C, meeting the needs of both domestic and commercial installations. All equipment is shipped directly from Spain and backed by Gaia Charge’s technical expertise.</p>\n<h2>A Comprehensive Resource for Installers, Businesses, and Homeowners</h2>\n<p>The new store is designed to serve a broad spectrum of users — from CPOs (Charge Point Operators) managing public or semi-public charging networks, to hospitality and retail venues, and individual homeowners seeking reliable charging solutions.</p>\n<p>Customers will find:</p>\n<ul>\n<li>EV chargers for residential and commercial use</li>\n<li>Accessories and components for new and existing installations</li>\n<li>Certified, ready-to-install equipment complying with Spanish and European standards</li>\n<li>Specialised advice and fast national shipping<br>By centralising access to high-quality hardware and expert support, Gaia Charge aims to remove barriers that often delay or complicate the rollout of EV charging points.</li>\n</ul>\n<h2>Supporting the Transition to Electric Mobility</h2>\n<p>The store reinforces Gaia Charge’s mission to provide turnkey EV charging solutions, complementing its existing portfolio of planning, installation, maintenance, and support services. It represents a key component in the company’s commitment to building a more integrated, reliable, and future-proof charging network.</p>\n<p>Quality, compatibility, and trust — guaranteed</p>\n",
  "language": "en"
};
</script>

<svelte:head>
{#if !$isLoading}
  <title>{post.frontmatter.title} - {$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/en/blog/gaia-charge-launches-online-store" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <article>
    <div class="headline z-40 text-center">
      <h1>
        {post.frontmatter.title}
      </h1>
      {#if post.frontmatter.date}
       <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
      {/if}
    </div>
    <div class="post mx-auto">
        {@html post.content}
    </div>
  </article>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .post {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  :global(p) {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }

  :global(blockquote) {
    background-color: #fff;
    padding: calc(20 / var(--ratio));
    font-style: italic;
    font-family: "New Spirit";
    border-left: 4px solid #65D45C;
  }
</style>
