<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../../components/Nav.svelte";
    import Footer from "../../../../components/Footer.svelte";
    export let data;
    const post = {
  "url": "/en/blog/gaia-charge-signs-agreement-with-last-mile-solutions",
  "frontmatter": {
    "title": "Gaia Charge and Last Mile Solutions Sign Bilateral Roaming Agreement",
    "date": "2025-07-28T00:00:00.000Z",
    "updated": "2025-08-11T10:02:00.000Z",
    "notion_id": "24ce5620-ab7b-80b5-84bc-d0235fd97998",
    "author": "Wojtek Siudzinski",
    "language": "english",
    "slug": "gaia-charge-signs-agreement-with-last-mile-solutions"
  },
  "content": "<p>Gaia Charge is pleased to announce the signing of a bilateral roaming agreement with Last Mile Solutions, one of Europe’s leading providers of electric mobility solutions.</p>\n<p>With over 240,000 operational charging points across 22 countries, Last Mile Solutions is a benchmark in the sector, offering intelligent charging management platforms that combine scalability, interoperability, and reliability.</p>\n<p>This two-way agreement allows Gaia Charge users to access a pan-European charging network seamlessly, while LMS users will be able to charge at Gaia’s network. A collaboration in both directions — just as it should be in an ecosystem that aims to be truly connected and accessible.</p>\n<blockquote>\n<p>“Building interoperability is not just about technology; it’s about partnerships that put drivers first,” said Wojtek Siudzinski, CEO of Gaia Charge. “With Last Mile Solutions, we share a vision of an open, connected charging infrastructure that works for everyone.”</p>\n</blockquote>\n<p>Gaia Charge continues to weave a broader, more integrated, and more useful network — for people and for the planet.</p>\n",
  "language": "en"
};
</script>

<svelte:head>
{#if !$isLoading}
  <title>{post.frontmatter.title} - {$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/en/blog/gaia-charge-signs-agreement-with-last-mile-solutions" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <article>
    <div class="headline z-40 text-center">
      <h1>
        {post.frontmatter.title}
      </h1>
      {#if post.frontmatter.date}
       <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
      {/if}
    </div>
    <div class="post mx-auto">
        {@html post.content}
    </div>
  </article>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .post {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  :global(p) {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }

  :global(blockquote) {
    background-color: #fff;
    padding: calc(20 / var(--ratio));
    font-style: italic;
    font-family: "New Spirit";
    border-left: 4px solid #65D45C;
  }
</style>
