<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../../components/Nav.svelte";
    import Footer from "../../../../components/Footer.svelte";
    export let data;
    const post = {
  "url": "/en/blog/gaia-charge-launches-mobile-app-for-mapa-reve",
  "frontmatter": {
    "title": "Gaia Charge launches new app to locate EV chargers across Spain",
    "date": "2025-05-15T00:00:00.000Z",
    "updated": "2025-08-11T10:02:00.000Z",
    "notion_id": "1f2e5620-ab7b-801d-9c3d-f018629a7d0e",
    "author": null,
    "language": "english",
    "slug": "gaia-charge-launches-mobile-app-for-mapa-reve"
  },
  "content": "<p>Valencia-based company Gaia Charge has launched its brand-new mobile app to help electric vehicle (EV) drivers easily locate public charging points across Spain.</p>\n<p>This app, independently developed by the Gaia Charge team, uses open data from the official MapaReve.es registry and offers a modern, streamlined experience focused on practical utility.</p>\n<blockquote>\n<p>“We know that charging can still be a frustrating experience for many EV drivers. We wanted to build something fast, simple and genuinely helpful—an app that makes it easy to find a compatible charger wherever you are,” said Wojtek Siudzinski, CEO of Gaia Charge.</p>\n</blockquote>\n<h2>Key features:</h2>\n<ul>\n<li>Search for public EV chargers across Spain</li>\n<li>Filter by power, connector type, payment method, price, and more</li>\n<li>View real-time availability</li>\n<li>Navigate directly with Google Maps, Apple Maps or Waze</li>\n<li>Fast and easy-to-use interface<br>The launch is part of Gaia Charge’s broader strategy to position itself as a leader in the EV sector—not only by operating its own infrastructure but also by improving access and transparency across the existing public charging network.</li>\n</ul>\n<blockquote>\n<p>“We want drivers not only to use our chargers, but to benefit from a network that works for everyone—even if the charging point isn’t operated by Gaia,” adds Siudzinski.</p>\n</blockquote>\n<p>The app is now available for download on both Android and iOS:</p>\n<p>👉 <a href=\"https://ggrn.link/app\">https://ggrn.link/app</a></p>\n",
  "language": "en"
};
</script>

<svelte:head>
{#if !$isLoading}
  <title>{post.frontmatter.title} - {$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/en/blog/gaia-charge-launches-mobile-app-for-mapa-reve" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <article>
    <div class="headline z-40 text-center">
      <h1>
        {post.frontmatter.title}
      </h1>
      {#if post.frontmatter.date}
       <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
      {/if}
    </div>
    <div class="post mx-auto">
        {@html post.content}
    </div>
  </article>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .post {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  :global(p) {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }

  :global(blockquote) {
    background-color: #fff;
    padding: calc(20 / var(--ratio));
    font-style: italic;
    font-family: "New Spirit";
    border-left: 4px solid #65D45C;
  }
</style>
