<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../../components/Nav.svelte";
    import Footer from "../../../../components/Footer.svelte";
    export let data;
    const post = {
  "url": "/es/blog/gaia-charge-y-last-mile-solutions-firman-un-acuerdo",
  "frontmatter": {
    "title": "Gaia Charge y Last Mile Solutions firman un acuerdo bilateral de roaming",
    "date": "2025-07-28T00:00:00.000Z",
    "updated": "2025-08-11T10:04:00.000Z",
    "notion_id": "24ce5620-ab7b-808b-8cad-e9f81f7c377a",
    "author": "Wojtek Siudzinski",
    "language": "spanish",
    "slug": "gaia-charge-y-last-mile-solutions-firman-un-acuerdo"
  },
  "content": "<p>En Gaia Charge nos complace anunciar la firma de un acuerdo bilateral de roaming con Last Mile Solutions, uno de los líderes europeos en soluciones de movilidad eléctrica.</p>\n<p>Con más de 240.000 puntos de recarga operativos en 22 países, Last Mile Solutions es un referente en ofrecer plataformas inteligentes para la gestión de la recarga, combinando escalabilidad, interoperabilidad y fiabilidad.</p>\n<p>Este acuerdo bidireccional permite que los usuarios de Gaia Charge accedan a una red paneuropea de recarga sin fricciones, al mismo tiempo que los usuarios de LMS podrán utilizar la red de Gaia. Una colaboración de doble vía, como debe ser en un ecosistema que aspira a ser verdaderamente conectado y accesible.</p>\n<blockquote>\n<p>“La interoperabilidad no se trata solo de tecnología; se trata de alianzas que ponen al conductor en el centro”, señaló Wojtek Siudzinski, CEO de Gaia Charge. “Con Last Mile Solutions compartimos la visión de una infraestructura de recarga abierta, conectada y al servicio de todos.”</p>\n</blockquote>\n<p>Gaia Charge sigue tejiendo una red más amplia, más integrada y más útil — para las personas y para el planeta.</p>\n",
  "language": "es"
};
</script>

<svelte:head>
{#if !$isLoading}
  <title>{post.frontmatter.title} - {$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/es/blog/gaia-charge-y-last-mile-solutions-firman-un-acuerdo" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <article>
    <div class="headline z-40 text-center">
      <h1>
        {post.frontmatter.title}
      </h1>
      {#if post.frontmatter.date}
       <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
      {/if}
    </div>
    <div class="post mx-auto">
        {@html post.content}
    </div>
  </article>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .post {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  :global(p) {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }

  :global(blockquote) {
    background-color: #fff;
    padding: calc(20 / var(--ratio));
    font-style: italic;
    font-family: "New Spirit";
    border-left: 4px solid #65D45C;
  }
</style>
