<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    export let data;
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../components/Nav.svelte";
    import Footer from "../../../components/Footer.svelte";
    import green_arrow_right from "$lib/assets/svg/green_arrow_right.svg";
    const posts = [
  {
    "url": "/es/blog/gaia-charge-firma-acuerdo-estrategico-con-evspot",
    "frontmatter": {
      "title": "Gaia Charge firma acuerdo estratégico con EVspot",
      "date": "2025-05-06T00:00:00.000Z",
      "updated": "2025-05-07T10:20:00.000Z",
      "notion_id": "1ebe5620-ab7b-800a-bd9a-d1338dbfb3ff",
      "author": "Santiago Muñoz Thomen",
      "language": "spanish",
      "slug": "gaia-charge-firma-acuerdo-estrategico-con-evspot"
    },
    "content": "<p>La empresa valenciana Gaia Charge, operadora independiente de puntos de recarga para vehículos eléctricos (CPO), anuncia la firma de un acuerdo estratégico con EVspot, compañía especializada en soluciones integrales de movilidad eléctrica, para la instalación de 120 nuevos cargadores en 37 ubicaciones distribuidas por toda España.</p>\n<blockquote>\n<p>“Este acuerdo marca un antes y un después para Gaia Charge”, afirma Wojtek Siudzinski, fundador y CEO. “Nuestra visión de una red de recarga funcional, transparente y centrada en el usuario se expande ahora con más fuerza, gracias a socios como EVspot.”</p>\n</blockquote>\n<p>Esta colaboración con EVspot, liderada por su CEO y fundador Ray Carballeira Gibson, fortalece el crecimiento de Gaia Charge a nivel nacional, consolidando su objetivo de crear una red de recarga fiable, accesible y alineada con las necesidades reales de los usuarios. Gaia Charge ya ha suministrado más de 750 MWh a más de 1.700 conductores, y continúa ampliando su presencia en nuevas regiones estratégicas.</p>\n<blockquote>\n<p>“En EVspot compartimos con Gaia Charge una visión clara: impulsar una movilidad eléctrica más accesible, eficiente y centrada en el usuario. Esta alianza refleja valores comunes, sinergia operativa y un compromiso conjunto con la sostenibilidad. Solo colaborando con socios así podemos acelerar esta transición.” compartido Carballeira Gibson.</p>\n</blockquote>\n",
    "language": "es"
  }
];
</script>

<svelte:head>
{#if !$isLoading}
  <title>{$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/es/blog" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <div>
    <div class="headline z-40 text-center">
      <h1>
        {$_("blog.index", {
            default: "Gaia Charge Blog",
        })}
      </h1>
    </div>
    <div class="posts-list mx-auto">
        {#each posts as post}
            <article class="post-card mx-auto mt-10 flex flex-row gap-4">
                <img src={green_arrow_right} class="inline-block fill-green" alt="To" />
                <div>
                    <h2 class="text-2xl font-serif"><a href="{post.url}">{post.frontmatter.title}</a></h2>
                    {#if post.frontmatter.date}
                        <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
                    {/if}
                    {#if post.frontmatter.description}
                        <p>{post.frontmatter.description}</p>
                    {/if}
                </div>
            </article>
        {/each}
    </div>
  </div>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .posts-list {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  p {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }
</style>
