<!--
    This file was automatically generated by the blog generator script.
    DO NOT EDIT THIS FILE DIRECTLY.
    To regenerate, run: npm run blog:generate
-->

<script>
    import { _, isLoading } from "svelte-i18n";
    import Nav from "../../../../components/Nav.svelte";
    import Footer from "../../../../components/Footer.svelte";
    export let data;
    const post = {
  "url": "/en/blog/gaia-charge-signs-strategic-agreement-with-evspot",
  "frontmatter": {
    "title": "Gaia Charge signs strategic agreement with EVspot",
    "date": "2025-05-06T00:00:00.000Z",
    "updated": "2025-05-12T16:24:00.000Z",
    "notion_id": "1f1e5620-ab7b-80f7-a3dc-c4568d407a5c",
    "author": "Santiago Muñoz Thomen",
    "language": "english",
    "slug": "gaia-charge-signs-strategic-agreement-with-evspot"
  },
  "content": "<p>The Valencian company Gaia Charge, an independent operator of charging points for electric vehicles (CPO), announces the signing of a strategic agreement with EVspot, a company specialized in integral electric mobility solutions, for the installation of 120 new chargers in 37 locations throughout Spain.</p>\n<blockquote>\n<p>“This agreement marks a before and after for Gaia Charge,” says Wojtek Siudzinski, founder and CEO. “Our vision of a functional, transparent and user-centric charging network is now expanding even more strongly, thanks to partners like EVspot.”</p>\n</blockquote>\n<p>This collaboration with EVspot, led by its CEO and founder Ray Carballeira Gibson, strengthens Gaia Charge&#39;s growth nationwide, consolidating its goal of creating a reliable, accessible recharging network aligned with the real needs of users. Gaia Charge has already supplied over 750 MWh to over 1,700 drivers, and continues to expand its presence in new strategic regions.</p>\n<blockquote>\n<p>&quot;At EVspot we share with Gaia Charge a clear vision: to drive more accessible, efficient and user-centric electric mobility. This alliance reflects common values, operational synergy and a joint commitment to sustainability. Only by collaborating with partners like this can we accelerate this transition,&quot; shared Carballeira Gibson.</p>\n</blockquote>\n",
  "language": "en"
};
</script>

<svelte:head>
{#if !$isLoading}
  <title>{post.frontmatter.title} - {$_("blog.index", {
      default: "Gaia Charge Blog",
    })}</title>
{/if}
  <link rel="canonical" href="https://gaiacharge.com/en/blog/gaia-charge-signs-strategic-agreement-with-evspot" />
</svelte:head>

<Nav />

{#if !$isLoading}
  <article>
    <div class="headline z-40 text-center">
      <h1>
        {post.frontmatter.title}
      </h1>
      {#if post.frontmatter.date}
       <time datetime={post.frontmatter.date}>{new Date(post.frontmatter.date).toLocaleDateString()}</time>
      {/if}
    </div>
    <div class="post mx-auto">
        {@html post.content}
    </div>
  </article>
{/if}

<Footer />

<style lang="postcss">
  .headline {
    padding-top: calc(179 / var(--ratio));
    padding-left: calc(380 / var(--ratio));
    padding-right: calc(380 / var(--ratio));
  }

  .headline h1 {
    font-family: theme("fontFamily.serif");
    font-size: calc(52 / var(--ratio));
    font-weight: 500;
    line-height: calc(57 / var(--ratio));
  }

  @media only screen and (max-width: 431px) {
    .headline {
      padding-top: 45%;
      padding-left: calc(200 / var(--ratio));
      padding-right: calc(200 / var(--ratio));
    }
  }

  .post {
      min-height: 50vh;
      max-width: calc(1008 / var(--ratio));
  }

  :global(p) {
    font-size: calc(18 / var(--ratio));
    line-height: calc(28 / var(--ratio));
    padding: calc(20 / var(--ratio));
    font-weight: 300;
  }

  :global(blockquote) {
    background-color: #fff;
    padding: calc(20 / var(--ratio));
    font-style: italic;
    font-family: "New Spirit";
    border-left: 4px solid #65D45C;
  }
</style>
